
#General Mod Config
[general]
	#Should the mod be enabled or not
	enabled = true
	#Enable Additional Logging. Used for Fault Finding. WARNING: CAUSES LOG SPAM!
	debugging = false
	#The active language to use for built in messages. Defaults to en_us if a language is not found
	language = "en_us"
	#Internal version control. DO NOT TOUCH!
	configVersion = 34

#Config specific to the discord bot
[botConfig]
	#The token of the Discord Bot to use. This will be encrypted on first load. See https://sdlink.fdd-docs.com/installation/bot-creation/ to find this
	botToken = "DcX01xY3uFGROvUXFFdft4t238bBom6iUZmoMmeY3hXrcneluC0yNgFvsTJxSvKG/btNmhy/rBi4C5USMWwwkpzDx0xv6sTxKr/pX2vkoYbCCWaemrrVQg=="
	#Print the bot invite link to the console on startup
	printInviteLink = false
	#Use silent replies when Slash Commands are used
	silentReplies = false
	#How often the Bot Status will update on Discord (in Seconds). Set to 0 to disable
	statusUpdateInterval = 30

	#Define how the bot should handle channel topic updates on the chat channel
	[botConfig.topicUpdates]
		#Should the bot update the topic of your chat channel automatically every 6 Minutes
		doTopicUpdates = true
		#How often should the bot update the channel topic (IN MINUTES)? CANNOT BE LOWER THAN 6 MINUTES!
		updateInterval = 6
		#A topic for the Chat Relay channel. You can use %player%, %maxplayers%, %uptime% or just leave it empty.
		channelTopic = "%players%/%maxplayers% players | Uptime: %uptime%"

	#Configure the in-game Discord Invite command
	[botConfig.invite]
		#If this is defined, it will enable the in-game Discord command
		inviteLink = ""
		#The message to show when someone uses /discord command. You can use %inviteurl%
		inviteMessage = "%inviteurl%"

	[[botConfig.botStatus]]
		status = "@MyIsekaiSMP | %players%/%maxplayers% players"
		botStatusType = "CUSTOM_STATUS"
		botStatusStreamingURL = "https://twitch.tv/myisekaismp"

#Config relating to the discord channels and webhooks to use with the mod
[channelsAndWebhooks]
	#A DIRECT link to an image to use as the avatar for server messages. Also used for embeds
	serverAvatar = "https://raw.githubusercontent.com/myisekaismp/raw-files/main/logo.png"
	#The name to display for Server messages when using Webhooks
	serverName = "My Life is an Isekai"

	#Config relating to the discord channels to use with the mod
	[channelsAndWebhooks.channels]
		#REQUIRED! The ID of the channel to post in and relay messages from. This is still needed, even in webhook mode
		chatChannelID = "1412158902207774830"
		#If this ID is set, event messages will be posted in this channel instead of the chat channel
		eventsChannelID = "1412158753473560807"
		#If this ID is set, console messages sent after the bot started will be relayed here
		consoleChannelID = "1412158732267290725"

	#Config relating to the discord Webhooks to use with the mod
	[channelsAndWebhooks.webhooks]
		#Prefer Webhook Messages over Standard Bot Messages
		enabled = true
		#Change how the webhook name is displayed in discord. Available placeholders: %display_name%, %mc_name%
		webhookNameFormat = "%display_name%"
		#Use Server Author for chat messages, instead of the real author information
		useServerForChat = false
		#The URL of the channel webhook to use for Chat Messages. Will be encrypted on first run
		chatWebhook = "ugon14PRUjyawLCfGyneVCmHl3KBEfBt47pb8UPWjJXvmmA3LaJomMbirZQNb5K9bh4VvyHUo9DG+aCaoNZcUKwGJdQhqptVeh+iFMz3cz6Le6g8T8TqdN3F3HoscQVhLoDN+T4/LVXmeODLme6qfQOchRVlu6aXdlXQBpjnZyjBOIZMdadR2Q=="
		#The URL of the channel webhook to use for Server Messages. Will be encrypted on first run
		eventsWebhook = "Kpgs0AUnAN2wK2Xk56BT7uVzkV0fttbAQyfGSsIsbo8dsTSKmwCiQBtgHimpK+EIYcbQVCpEsdmrOElxy4O92QTyfO0V6fzd81vknJLO64zaByEqv6dF2o/xTusnyd+1/vfmmwEMI9T2yAKsr5kcTFrvHQkyQcjZ3XkPAY+pyCOnD0ouSOKVAg=="
		#The URL of the channel webhook to use for Console Messages. DOES NOT WORK FOR CONSOLE RELAY! Will be encrypted on first run
		consoleWebhook = "NFaxkLPkAbrFB0yeh58EX/aTzqwjYK/BJvZZUNjI6cuNHQ/DPz0Owm4yOeG6XBKU4X5QwjuhcSAmyOOBMSHLY/ztGrllfzE0xTahEv0LTFNt9wmVe/bfVc0kjSiRrzlHL2qqeHCnr4rbJdVzXvM2eubTnH+3cyz3ZVvcWJH740YRcFqomX64+A=="

#Configure which types of messages are delivered to Minecraft/Discord
[chat]
	#Use linked account names in Discord/Minecraft messages, instead of the default ones
	useLinkedNames = false
	#Show the discord name, username and role of the user that sent a message in Minecraft when the message is hovered
	showDiscordInfo = false
	#Convert Discord to MC, and MC to Discord Formatting
	formatting = true
	#Should console messages be sent to the Console Channel
	sendConsoleMessages = true
	#Add your own Avatar service URL here. Use {uuid} to replace the player ID in the URL
	customAvatarService = "https://crafatar.com/avatars/{uuid}&overlay"
	#The type of image to use as the player icon in messages. Valid entries are: AVATAR, HEAD, BODY, COMBO, CUSTOM
	playerAvatarType = "HEAD"
	#Should messages sent with TellRaw be sent to discord as a chat? (Experimental)
	relayTellRaw = true
	#Should the entire command executed be relayed to discord, or only the name of the command
	relayFullCommands = true
	#Should messages from bots be relayed
	ignoreBots = true
	#Compatibility with PluralKit (can introduce a very slight delay in messages being sent from Discord to Minecraft)
	pluralKitCompat = false
	#Amount of time to delay messages by before sending them to Minecraft in milliseconds. Too low may make unproxied messages visible and too high will cause noticeable delay.
	pluralKitCompatMessageDelay = 500
	#Should SERVER STARTING messages be shown
	serverStarting = true
	#Should SERVER STARTED messages be shown
	serverStarted = true
	#Should SERVER STOPPING messages be shown
	serverStopping = false
	#Should SERVER STOPPED messages be shown
	serverStopped = false
	#Should the chat be relayed
	playerMessages = true
	#Should discord messages be relayed to Minecraft
	discordMessages = true
	#Should Player Join messages be posted
	playerJoin = true
	#Should Player Leave messages be posted
	playerLeave = true
	#Should Advancement messages be posted. Valid values are ALWAYS, NEVER or GAMERULE
	advancementMessages = "NEVER"
	#Should Death Announcements be posted. Valid values are ALWAYS, NEVER or GAMERULE
	deathMessages = "ALWAYS"
	#Should Messages from the /say command be posted
	sendSayCommand = true
	#Should commands be posted to discord
	broadcastCommands = false
	#Should whitelist changes be posted to discord
	whitelistChanged = true
	#Commands that should not be broadcast to discord
	ignoredCommands = ["particle", "login", "execute", "sdconfigeditor", "title", "effect"]
	#Allow mentioning discord roles and users from Minecraft Chat
	allowMentionsFromChat = false

#Change the format in which messages are displayed
[messageFormatting]
	#Prefix to add to Minecraft when a message is relayed from Discord. Supports MiniMessage formatting. Use %user% for the Discord Username
	mcPrefix = "<yellow>[Discord]<reset> %user%: "
	#How messages relayed from discord that are replies to other messages are formatted. Supports MiniMessage formatting
	mcReplyFormatting = "    <b>┌────<reset> %color%@%replier_name%%end_color% <gray>%message_summary%<newline><reset>"
	#Server Starting Message
	serverStarting = "*Iniciando...*"
	#Server Started Message
	serverStarted = "*Online!*"
	#Server Stopping Message
	serverStopping = "*Encerrando...*"
	#Server Stopped Message
	serverStopped = "*Offline!*"
	#Player Joined Message. Use %player% to display the player name
	playerJoined = "**%player%** entrou no servidor"
	#Player Left Message. Use %player% to display the player name
	playerLeft = "**%player%** saiu do servidor"
	#Advancement Messages. Available variables: %player%, %title%, %description%
	advancements = "*%player% has made the advancement [%title%]: %description%*"
	#Chat Messages. THIS DOES NOT APPLY TO EMBED OR WEBHOOK MESSAGES. Available variables: %player%, %message%, %mcname%
	chat = "%player%: %message%"
	#Death Messages. Available variables: %player%, %message%
	death = "%player% %message%"
	#Message to be sent when a player is added to the whitelist
	whitelistAdded = "%player% has been whitelisted!"
	#Message to be sent when a player is removed from the whitelist
	whitelistRemoved = "%player% has been removed from the whitelist!"
	#Command Messages. Available variables: %player%, %command%
	commands = "%player% **executed command**: *%command%*"

#Change in which channel messages appear
[messageDestinations]

	#Control where CHAT messages are delivered
	[messageDestinations.chat]
		#The Channel the message will be delivered to. Valid entries are CHAT, EVENT, CONSOLE, OVERRIDE
		channel = "CHAT"
		#Should the message be sent using EMBED style messages
		useEmbed = false
		#Embed Layout to use
		embedLayout = "default"
		#Override the destination with a custom channel/webhook url. Make sure to change `channel` above to OVERRIDE
		override = ""

	#Control where START messages are delivered
	[messageDestinations.start]
		#The Channel the message will be delivered to. Valid entries are CHAT, EVENT, CONSOLE, OVERRIDE
		channel = "CHAT"
		#Should the message be sent using EMBED style messages
		useEmbed = true
		#Embed Layout to use
		embedLayout = "default"
		#Override the destination with a custom channel/webhook url. Make sure to change `channel` above to OVERRIDE
		override = ""

	#Control where STOP messages are delivered
	[messageDestinations.stop]
		#The Channel the message will be delivered to. Valid entries are CHAT, EVENT, CONSOLE, OVERRIDE
		channel = "CHAT"
		#Should the message be sent using EMBED style messages
		useEmbed = true
		#Embed Layout to use
		embedLayout = "default"
		#Override the destination with a custom channel/webhook url. Make sure to change `channel` above to OVERRIDE
		override = ""

	#Control where JOIN messages are delivered
	[messageDestinations.join]
		#The Channel the message will be delivered to. Valid entries are CHAT, EVENT, CONSOLE, OVERRIDE
		channel = "EVENT"
		#Should the message be sent using EMBED style messages
		useEmbed = false
		#Embed Layout to use
		embedLayout = "default"
		#Override the destination with a custom channel/webhook url. Make sure to change `channel` above to OVERRIDE
		override = ""

	#Control where LEAVE messages are delivered
	[messageDestinations.leave]
		#The Channel the message will be delivered to. Valid entries are CHAT, EVENT, CONSOLE, OVERRIDE
		channel = "EVENT"
		#Should the message be sent using EMBED style messages
		useEmbed = false
		#Embed Layout to use
		embedLayout = "default"
		#Override the destination with a custom channel/webhook url. Make sure to change `channel` above to OVERRIDE
		override = ""

	#Control where ADVANCEMENT messages are delivered
	[messageDestinations.advancements]
		#The Channel the message will be delivered to. Valid entries are CHAT, EVENT, CONSOLE, OVERRIDE
		channel = "EVENT"
		#Should the message be sent using EMBED style messages
		useEmbed = false
		#Embed Layout to use
		embedLayout = "default"
		#Override the destination with a custom channel/webhook url. Make sure to change `channel` above to OVERRIDE
		override = ""

	#Control where DEATH messages are delivered
	[messageDestinations.death]
		#The Channel the message will be delivered to. Valid entries are CHAT, EVENT, CONSOLE, OVERRIDE
		channel = "EVENT"
		#Should the message be sent using EMBED style messages
		useEmbed = false
		#Embed Layout to use
		embedLayout = "default"
		#Override the destination with a custom channel/webhook url. Make sure to change `channel` above to OVERRIDE
		override = ""

	#Control where COMMAND messages are delivered
	[messageDestinations.commands]
		#The Channel the message will be delivered to. Valid entries are CHAT, EVENT, CONSOLE, OVERRIDE
		channel = "EVENT"
		#Should the message be sent using EMBED style messages
		useEmbed = false
		#Embed Layout to use
		embedLayout = "default"
		#Override the destination with a custom channel/webhook url. Make sure to change `channel` above to OVERRIDE
		override = ""

	#Control where WHITELIST change messages are delivered
	[messageDestinations.whitelist]
		#The Channel the message will be delivered to. Valid entries are CHAT, EVENT, CONSOLE, OVERRIDE
		channel = "EVENT"
		#Should the message be sent using EMBED style messages
		useEmbed = true
		#Embed Layout to use
		embedLayout = "default"
		#Override the destination with a custom channel/webhook url. Make sure to change `channel` above to OVERRIDE
		override = ""

	#Control where messages that match none of the above are delivered
	[messageDestinations.custom]
		#The Channel the message will be delivered to. Valid entries are CHAT, EVENT, CONSOLE, OVERRIDE
		channel = "EVENT"
		#Should the message be sent using EMBED style messages
		useEmbed = false
		#Embed Layout to use
		embedLayout = "default"
		#Override the destination with a custom channel/webhook url. Make sure to change `channel` above to OVERRIDE
		override = ""

#Manage access to your server, similar to whitelisting
[accessControl]
	#Enable Access Control
	enabled = false
	#Allow users to verify their accounts without access control. This setting is ignored if the above setting is set to true
	optionalVerification = false
	#Does the player need to be a member of your discord to join
	requireDiscordMembership = false
	#Can players verify multiple Minecraft Accounts
	allowMultipleAccounts = false
	#Change the discord user nickname to their Minecraft name when their accounts are linked
	changeDiscordNickname = false
	#Optional: The player requires any of these roles to be able to join your server
	requiredRoles = []
	#Optional: Players with these roles will never be allowed access to your server
	deniedRoles = []
	#Optional: Role name or ID to assign to verified player accounts
	verifiedRole = []
	#Should players with verified accounts, be banned from Minecraft if they get banned on discord
	banPlayerOnDiscordBan = false
	#Should members with verified accounts, be banned from discord when they are banned on Minecraft
	banMemberOnMinecraftBan = false

	#Configure messages shown to players when they don't meet verification requirements
	[accessControl.verificationMessages]
		#This message is shown to users when they use the in-game verification command
		optionalVerificationMessage = "Your verification code is: {code}. Please DM our bot, or use the /verify command in our discord to verify your account"
		#The message shown to players that are not verified
		accountVerification = "This server requires account verification. Your verification code is: {code}. Please visit our discord server for instructions on how to verify your account."
		#Message to show to players that are not a member of your discord
		nonMember = "Sorry, you need to be a member of our discord server to join this server"
		#Message to show when player doesn't have one of the required roles. Use {roles} to display the names of configured roles
		requireRoles = "Sorry, but you require any of the following roles: {roles}"
		#Message to show when player has a role from the deniedRoles list
		roleDenied = "Sorry, but you are not allowed to access this server."

#Execute Minecraft commands in Discord
[minecraftCommands]
	#Allow executing Minecraft commands from Discord
	enabled = true
	#Command Prefix. For example ?weather clear
	prefix = "~"
	#Should command replies be deleted automatically or not
	keepReplies = true
	#Should the original message that was sent to trigger the command be deleted automatically or not
	keepOriginal = true
	#Should error messages be sent for invalid, or disallowed commands
	outputInvalid = true
	#You can leave this empty, or enter the channel ID's (surrounded by "") of channels where linked commands can be used
	allowedChannels = ["1413529651380224121", "1412158753473560807", "1412158732267290725"]

	[[minecraftCommands.permissions]]
		role = "1412160079796375663"
		commands = []
		permissionLevel = 4

#Configure message/username filtering for discord messages
[filtering]
	#Enable the filter system
	enabled = false
	#List of entries to process
	entries = []
	#Ignore messages sent from certain threads. Enable debug logging to see what thread the message is from
	ignoredThreads = []

#Run Minecraft commands when discord roles changes. Requires Access Control to be enabled
[triggerCommands]
	#Should any of the below commands be executed when a role changes
	enabled = false
	#Commands to run when roles are added
	roleAdded = []
	#Commands to run when roles are removed
	roleRemoved = []

