
["Configs for Proximity Text Chat"]
	#How close you have to be to see other's messages
	Range = 20000
	#Toggles distortion mode
	"Distortion Mode Toggle" = false
	#How close you have to be to see other's messages missing some words
	"Distortion Range" = 30000
	#Word that missing words are replaced with in distortion mode
	"Distortion Phrase" = "*incompreens√≠vel*"
	#Toggles Underscore mode, where letters of the word are replaced with underscores
	"Underscore Mode" = true

